apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amitiamity/argocd-course-webapp-config.git'
    targetRevision: main
    path: helm/webapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true